### ISSUE TITLE
How to extract point cloud?

### ISSUE THREAD

**Issue by liu-zg15** [tum-vision/LDSO#10]
Hi, I compiled the algorithm on TUM datasets.
I've got some good results and I want to extract the point cloud from LDSO for using it in a visualizer(such as meshlab).
I have got a method in DSO:  https://github.com/JakobEngel/dso/issues/55
But when I try to do it in LDSO, I found the code changes a lot. 
Has anyone success to extract the point cloud by LDSO? Can you help us? I think it will be helpful for many people!

**Comment by gaoxiang12** [comment]
If you mean the visualized point cloud, it is stored in frontend/DSOViewer and is almost same with DSO. DSOViewer has a vector KeyframeDisplay structure which render the displayed point cloud.

You can also get access to the map points in each frame through fullSystem->allFrameHistory and build the point cloud. It should look more sparse than the visualized one since each map point is rendered as eight pixels in the DSOViewer.

**Comment by jwangjie** [comment]
@gaoxiang12 , Hi Xiang shen,

Thanks a lot for your work making DSO a full SLAM algorithm. 

Your codes run very well. I was trying to save point clouds as a pcl file. I tried to follow the solutions mentioned in [JakobEngel/dso#55](https://github.com/JakobEngel/dso/issues/55) by changing line 117 
`void publishKeyframes(std::vector<shared_ptr<Frame>> &frames, bool final, shared_ptr<CalibHessian> HCalib);` of [LDSO/include/frontend/DSOViewer.h](https://github.com/tum-vision/LDSO/blob/master/include/frontend/DSOViewer.h) to
```
void publishKeyframes( std::vector<FrameHessian*> &frames, bool final, CalibHessian* HCalib)
        {
            float fx = HCalib->fxl();
            float fy = HCalib->fyl();
            float cx = HCalib->cxl();
            float cy = HCalib->cyl();
            float fxi = 1/fx;
            float fyi = 1/fy;
            float cxi = -cx / fx;
            float cyi = -cy / fy;

            // Open stream to write in file "points.ply"
            std::ofstream output_points;
            output_points.open("points.ply", std::ios_base::app);

            for(FrameHessian* f : frames)
            {
                printf("OUT: KF %d (%s) (id %d, tme %f): %d active, %d marginalized, %d immature points. CameraToWorld:\n",
                       f->frameID,
                       final ? "final" : "non-final",
                       f->shell->incoming_id,
                       f->shell->timestamp,
                       (int)f->pointHessians.size(), (int)f->pointHessiansMarginalized.size(), (int)f->immaturePoints.size());
                std::cout << f->shell->camToWorld.matrix3x4() << "\n";


                int maxWrite = 5;
                for(PointHessian* p : f->pointHessians)
                {
                    printf("OUT: Example Point x=%.1f, y=%.1f, idepth=%f, idepth std.dev. %f, %d inlier-residuals\n",
                           p->u, p->v, p->idepth_scaled, sqrt(1.0f / p->idepth_hessian), p->numGoodResiduals );
                    maxWrite--;
                    if(maxWrite==0) break;
                }

                auto const & m =  f->shell->camToWorld.matrix3x4();
                auto const & points = f->pointHessiansMarginalized;

                for (auto const * p : points) {
                  float depth = 1.0f / p->idepth;
                  auto const x = (p->u * fxi + cxi) * depth;
                  auto const y = (p->v * fyi + cyi) * depth;
                  auto const z = depth * (1 + 2*fxi);

                  Eigen::Vector4d camPoint(x, y, z, 1.f);
                  Eigen::Vector3d worldPoint = m * camPoint;

                  output_points << worldPoint.transpose() << std::endl;
                }
            }

            // Close steam
            output_points.close();
        }
```
Some compile errors popped up for sure. I was wondering can you do a quick review of the codes to make it works? Many thanks in advance.

Regards,
Jie

**Comment by liu-zg15** [comment]
Thank you very much. @gaoxiang12 
I think this issue can be closed. Cause the authors have added a function to save point clouds.
Thank you again for impressive work.
