### ISSUE TITLE
realtime running

### ISSUE THREAD

**Issue by GentlemanCheng** [tum-vision/LDSO#11]
Hello, I want to learn how to run this great demo realtimely by ros. Is there some exemple for it ? looking forward to your answer. Thanks!

**Comment by FPSychotic** [comment]
some news about can run it from a video topic of ros?

**Comment by NikolausDemmel** [comment]
No, I'm sorry but there is no ROS version yet and I don't think anyone is working on it. You'd have to integrate it yourself.

**Comment by FPSychotic** [comment]
Ohh, that is out of my capabilies Im just a hobbyist. Thanks for share

**Comment by NikolausDemmel** [comment]
I'll close this, since there are no concrete plans to implement this. If you want to keep discussing details of ROS integration, we can reopen or create a new issue.
