### ISSUE TITLE
Not closed on my own sequence

### ISSUE THREAD

**Issue by liu-zg15** [tum-vision/LDSO#16]
Hi, Thank you for this impressive work. I tried to use this on my own sequence. But I found it cannot be closed after a full loop. I don't whats happening. Could anyone help me?
I run 
`./bin/run_dso_tum_mono preset=0 setting_enableLoopClosing=true setting_pointSelection=1 files=/media/gone/Elements/TO_DSO/calibratedRADIO/images/ vignette=/home/gone/calib/radio/vignette.png calib=/home/gone/calib/radio/camera.txt gamma=/home/gone/calib/radio/pcalib.txt`
in command.
No error happens but the result is just like below:
![loop1](https://user-images.githubusercontent.com/22762508/52239559-bf3d8500-289c-11e9-9b2d-c71ef06be83d.png)
![loop2](https://user-images.githubusercontent.com/22762508/52239569-c5336600-289c-11e9-8875-4b043f37a89a.png)
The command window just show this:
![loop3](https://user-images.githubusercontent.com/22762508/52239789-468af880-289d-11e9-8acf-e3e2d959532f.png)
Is there anything I missed?

**Comment by gaoxiang12** [comment]
Hi @liu-zg15 The parameters about loop closing in LDSO in set to be a quite strict value to prevent false loops in our dataset, so many possible loops will be rejected during loop closure detection.  You can adjust those parameters if the correct loop is not detected in your data. Taking a quick look of frontend/LoopClosing would be helpful.

**Comment by liu-zg15** [comment]
Hi @gaoxiang12 . I really appreciate your reply.
I think you are right. The parameters about loop closing in LDSO are set to be very strict.
Changing some parameters in LoopClosing.cpp is the easiest way.(It works in my sequence) But be careful!. False loop will cause failure of whole procedure. I suggest to calibrate your camera more careful.

**Comment by amiltonwong** [comment]
Hi, @liu-zg15 and @gaoxiang12,

Which code should I modify for adapting my sequence (images located in a directory) as input source? Any hints for the modification?

THX!

**Comment by NikolausDemmel** [comment]
@amiltonwong, I'm not sure this is related to this issue?

If your sequence is in one of the supported formats, just point to it with command line arguments. Or else implement your custom DatasetReader. Check the different executables in `examples`.
