### ISSUE TITLE
Double join cause the 

### ISSUE THREAD

**Issue by charles200000** [tum-vision/LDSO#17]
https://github.com/tum-vision/LDSO/blob/ae401bb7c68d4a6df02d227815bab9d8c8850582/src/frontend/DSOViewer.cc#L336

This line cause the program to crash
the mainthread is already in use

you need to change it to :+1: 

`if (runThread.is_callable())
                   runThread.join()`

**Comment by NikolausDemmel** [comment]
Thanks, you are right. But looks like some more changes are needed for a clean exit. See #18
