### ISSUE TITLE
Throw cv::Exception when running on EuRoC V2_03 dataset

### ISSUE THREAD

**Issue by Beniko95J** [tum-vision/LDSO#22]
The log looks like:
...
I0417 02:07:15.490262 66300 FullSystem.cc:574] marg frame 167
I0417 02:07:15.494781 66300 FullSystem.cc:586] make keyframe done
I0417 02:07:15.494812 66300 FullSystem.cc:155] add active frame returned

I0417 02:07:15.497190 66299 LoopClosing.cc:125] candidate kf id: 6, max id: 17, min id: 7
I0417 02:07:15.497284 66299 LoopClosing.cc:140] add loop candidate from 6, current: 18, score: 0.0696457
I0417 02:07:15.497807 66299 LoopClosing.cc:166] matches: 30
OpenCV Error: Assertion failed (confidence > 0 && confidence < 1) in run, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/calib3d/src/ptsetreg.cpp, line 178
I0417 02:07:15.498713 66300 FullSystem.cc:73] *** taking frame 178 ***
I0417 02:07:15.500759 66300 FullSystem.cc:107] swap coarse tracker to 177
I0417 02:07:15.500782 66300 FullSystem.cc:114] tracking new frame
I0417 02:07:15.502157 66300 FullSystem.cc:378] Coarse Tracker tracked ab = -0.0482893 4.53887 (exp 1 ). Res 2.57252
I0417 02:07:15.502806 66300 FullSystem.cc:153] deliver frame 178
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/calib3d/src/ptsetreg.cpp:178: error: (-215) confidence > 0 && confidence < 1 in function run

[1]    66291 abort (core dumped)  ./bin/run_dso_euroc preset=0

Does anyone knows how to solve this? I think V2_03 dataset is kind of challenging and i want to know whether this core dumped is caused by the difficulty of the dataset, or it is a coding issue?

Thank you very much.

**Comment by Beniko95J** [comment]
Update:

Same issue happens when running on V2_02. Sorry but may I ask what does this code

 (confidence > 0 && confidence < 1) 

check?

Thanks!

**Comment by liu-zg15** [comment]
You can check the closed issue.
#21 
 I think it's the same problem. @Beniko95J

**Comment by NikolausDemmel** [comment]
@Beniko95J Are you using latest master? That should include the fix described in #21, see #18.

**Comment by NikolausDemmel** [comment]
I guess the issue wasn't fixed for OpenCV 3 and 4 on master after all. See #24 and maybe try if `niko-devel` works for you.

**Comment by Beniko95J** [comment]
@liu-zg15 Thanks. This solved my problem!
@NikolausDemmel  Thank you for the replies. It seems to be a problem caused by different versions of function cv::solvePnPRansac() in OpenCV2 and OpenCV3.
