### ISSUE TITLE
OpenCV version to 4.0. But software works first and ends in a very short time

### ISSUE THREAD

**Issue by yolingen23** [tum-vision/LDSO#23]
my git status: `gurturk@gurturk:~/Downloads$ git status LDSO-master/
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
`

 When installing the software . i did not  get any error.

this is my code;

`./bin/run_dso_tum_mono     
preset=0     files=/home/gurturk/Downloads/sequence_17/images.zip     vignette=/home/gurturk/Downloads/sequence_17/vignette.png     calib=/home/gurturk/Downloads/sequence_17/camera.txt     gamma=/home/gurturk/Downloads/sequence_17/pcalib.txt
`
i came across this result;

``I0502 15:50:15.658877  5582 LoopClosing.cc:125] candidate kf id: 41, max id: 96, min id: 75
I0502 15:50:15.658922  5582 LoopClosing.cc:133] add loop candidate from 41, current: 97, score: 0.046042
I0502 15:50:15.659015  5582 LoopClosing.cc:166] matches: 19
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.0) /home/gurturk/opencv/modules/calib3d/src/ptsetreg.cpp:167: error: (-215:Assertion failed) confidence > 0 && confidence < 1 in function 'run'`

Aborted (core dumped)
`

**Comment by NikolausDemmel** [comment]
> ... and include the output of `git status`, `cmake` ...

**Comment by yolingen23** [comment]
`gurturk@gurturk:~/LDSO$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/frontend/ImageRW_OpenCV.cc

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	built.dir/

no changes added to commit (use "git add" and/or "git commit -a")
`
cmakelists.txt ;


`gurturk@gurturk:~/LDSO$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/frontend/ImageRW_OpenCV.cc

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	built.dir/

no changes added to commit (use "git add" and/or "git commit -a")
`

**Comment by NikolausDemmel** [comment]
```
git log -n 1
```

and

```
cd build
cmake .
```

**Comment by yolingen23** [comment]
`gurturk@gurturk:~/LDSO$ git log -n 1
commit 5a4f6563ca64805d14db7ab9cba084445ba8060c (HEAD -> master, origin/master, origin/HEAD)
Merge: ae401bb b05892f
Author: Xiang Gao <gaoxiang12@mails.tsinghua.edu.cn>
Date:   Wed Feb 27 12:31:42 2019 +0800

    Merge pull request #18 from tum-vision/downstream_fixes
    
    Downstream fixes
`
gurturk@gurturk:~/LDSO/build$ cmake .
--- found ziplib (1.1.2), compiling with zip capability.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gurturk/LDSO/build

**Comment by NikolausDemmel** [comment]
Wait, I just noticed it's actually not fixed correctly on master. Can you try with branch `niko-devel`?
