### ISSUE TITLE
About trajectory estimation

### ISSUE THREAD

**Issue by GentlemanCheng** [tum-vision/LDSO#26]
Hi @NikolausDemmel , I want to have a try to estimate this repo, but what confused me is I don't know how to save and extract the trajectory generated finally as a file to compare with groundth by other tools. Is there any corresponding code for saving and extracting trajectory? Could you give me some suggestions? Thank you very much !

**Comment by NikolausDemmel** [comment]
Please don't cross-post the same question multiple times.

Sorry, but to be frank, I don't have time for such a vague question. As mentioned before, there is a `results.txt` generated with the trajectory. You can check in the code how it is done.

**Comment by GentlemanCheng** [comment]
@NikolausDemmel  I'm sorry about it, I have found from code yesterday. Thank you!
