### ISSUE TITLE
Segment fault problem

### ISSUE THREAD

**Issue by LittleByLittle2** [tum-vision/LDSO#3]
Hi, I already build the project successfully and got the execution program, but when I ran ./bin/run_dso_kitti, I got segment fault problem.  I use data sets from Kiiti odometry,

I want to know when the program will get Segment Fault situation and how do I address this issue.

Thank you,

Like below:

PHOTOMETRIC MODE WITHOUT CALIBRATION!
Reading Calibration from file /home/yuu/Downloads/kitti_odometry/dataset/sequences/02/camera.txt ... found!
found PINHOLE camera model, building rectifier.
Input resolution: 1241 367
In: 718.856000 718.856000 607.192800 185.215700 0.000000

Out: No Rectification
Output resolution: 1241 367

Rectified Kamera Matrix:
718.856       0 607.193
      0 718.856 185.216
      0       0       1

NO PHOTOMETRIC Calibration!
Reading Photometric Calibration from file
PhotometricUndistorter: Could not open file!
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1024 15:18:09.670336  5237 DatasetReader.h:286] Loading Kitti timestamps!
I1024 15:18:09.670459  5237 DatasetReader.h:292] cannot find timestamp file at /home/yuu/Downloads/kitti_odometry/dataset/sequences/02/image_0/times.txt
using pyramid levels 0 to 0. coarsest resolution: 1241 x 367!

===============WARNING!===================
 I need higher resolution.
I will probably segfault.
I1024 15:18:10.360255  5237 FullSystem.cc:34] This is Direct Sparse Odometry, a fully direct VO proposed by TUM vision group.For more information about dso, see Direct Sparse Odometry, J. Engel, V. Koltun, D. Cremers, In arXiv
:1607.02565, 2016. For loop closing part, see LDSO: Direct Sparse Odometry with Loop Closure, X. Gao, R. Wang, N. Demmel, D. Cremers, In International Conference on Intelligent Robots and Systems (IROS), 2018
I1024 15:18:10.483799  5237 FullSystem.cc:51] Use fast loop closing
I1024 15:18:10.484431  5247 LoopClosing.h:67] wait loop closing to join
I1024 15:18:10.488888  5246 LoopClosing.cc:44] find loop closing thread need finish flag!
I1024 15:18:10.488950  5247 LoopClosing.h:82] Loop closing thread is finished
I1024 15:18:10.488962  5247 FullSystem.cc:1935] saving kitti trajectory...
I1024 15:18:10.489017  5247 FullSystem.cc:1963] done.
I1024 15:18:10.489032  5247 FullSystem.cc:1935] saving kitti trajectory...
I1024 15:18:10.489048  5247 FullSystem.cc:1963] done.
Segmentation fault (core dumped)

**Comment by LittleByLittle2** [comment]
I know the input is not right.

**Comment by LittleByLittle2** [comment]
> I got the same problem. But how to correct the input dataset？

Maybe it's about your image path, this kind of small typo.

**Comment by ns15417** [comment]
@zhanqan it is said on the log that "cannot find timestamp file at /home/yuu/Downloads/kitti_odometry/dataset/sequences/02/image_0/times.txt", so the segFault is because of the wrong reading of file times.txt. If you have the same problem, you can check your input file path.
