### ISSUE TITLE
Segmentation fault when running through FeatureDetector::DetectCorners function

### ISSUE THREAD

**Issue by minghanz** [tum-vision/LDSO#30]
I am running a 1920*1080 image sequence captured by myself. The path are configured correctly, and the algorithm successfully initialized and ran for a while, but stopped in the middle showing a "Segmentation fault (core dumped)" error. 

By adding more print outs I locate that the error occurs in the following _for_ loop at the end of function **FeatureDetector::DetectCorners** in FeatureDetector.cc: 
```
for (auto &feat: frame->features) {
        if (feat->isCorner) {
            feat->angle = IC_Angle(
                    frame->frameHessian->dIp[feat->level], Vec2f(feat->uv[0], feat->uv[1]), feat->level);
            ComputeDescriptor(frame, feat);
            cntCornerSelected++;
        }
      }
```
Any clues on the possible cause of the problem? Any help is appreciated! 

The calibration file I used is as following:
```
RadTan 2295.199 2334.593 912.909 473.102 -0.638358 0.320621 0.00050989 0.010952
1920 1080
crop
1792 1024
```
Originally I used "1920 1080" for the last line, but there is a warning saying pyramid level may be too few. The "1792 1024" result in 5 pyramid levels and the warning is gone. Both settings of the last line meet the same segmentation fault. 

When I run GDB, it shows the following:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000048f473 in ldso::FeatureDetector::DetectCorners(int, std::shared_ptr<ldso::Frame>&) ()
[Current thread is 1 (Thread 0x7fbab5e9f700 (LWP 23654))]
(gdb) where
#0  0x000000000048f473 in ldso::FeatureDetector::DetectCorners(int, std::shared_ptr<ldso::Frame>&) ()
#1  0x0000000000464a1e in ldso::FullSystem::makeNewTraces(std::shared_ptr<ldso::internal::FrameHessian>, float*) ()
#2  0x0000000000470e63 in ldso::FullSystem::makeKeyFrame(std::shared_ptr<ldso::internal::FrameHessian>) ()
#3  0x0000000000472a1c in ldso::FullSystem::deliverTrackedFrame(std::shared_ptr<ldso::internal::FrameHessian>, bool) ()
#4  0x00000000004731b5 in ldso::FullSystem::addActiveFrame(ldso::ImageAndExposure*, int) ()
#5  0x000000000045434f in main::{lambda()#1}::operator()() const [clone .constprop.303] ()
#6  0x00007fbadc8a6c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fbadcb776ba in start_thread (arg=0x7fbab5e9f700)
    at pthread_create.c:333
#8  0x00007fbadc00c41d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by NikolausDemmel** [comment]
Could be related to a missing image bounds check. Please try the proposed changes mentioned in this issue: https://github.com/tum-vision/LDSO/issues/15#issuecomment-467350760

**Comment by minghanz** [comment]
Problem solved. Thanks! 
Please refer to the above message for solution.
