### ISSUE TITLE
/usr/bin/ld: cannot find -lwayland-egl

### ISSUE THREAD

**Issue by match08** [tum-vision/LDSO#31]
[ 81%] Built target ldso
[ 84%] Linking CXX executable ../../bin/run_dso_euroc
[ 87%] Linking CXX executable ../../bin/run_dso_kitti
[ 90%] Linking CXX executable ../../bin/run_dso_tum_mono
/usr/bin/ld: cannot find -lwayland-egl
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
examples/CMakeFiles/run_dso_euroc.dir/build.make:173: recipe for target '../bin/run_dso_euroc' failed
make[2]: *** [../bin/run_dso_euroc] Error 1
CMakeFiles/Makefile2:181: recipe for target 'examples/CMakeFiles/run_dso_euroc.dir/all' failed
make[1]: *** [examples/CMakeFiles/run_dso_euroc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lwayland-egl
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
examples/CMakeFiles/run_dso_tum_mono.dir/build.make:173: recipe for target '../bin/run_dso_tum_mono' failed
make[2]: *** [../bin/run_dso_tum_mono] Error 1
CMakeFiles/Makefile2:144: recipe for target 'examples/CMakeFiles/run_dso_tum_mono.dir/all' failed
make[1]: *** [examples/CMakeFiles/run_dso_tum_mono.dir/all] Error 2
/usr/bin/ld: cannot find -lwayland-egl
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
examples/CMakeFiles/run_dso_kitti.dir/build.make:173: recipe for target '../bin/run_dso_kitti' failed
make[2]: *** [../bin/run_dso_kitti] Error 1
CMakeFiles/Makefile2:218: recipe for target 'examples/CMakeFiles/run_dso_kitti.dir/all' failed
make[1]: *** [examples/CMakeFiles/run_dso_kitti.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by NikolausDemmel** [comment]
Looks like you might be missing a Pangolin dependency. I think the wayland support was added recently, so documentation might not be up to date.

You can try the folllowing if you are on ubuntu:

```
sudo apt install libegl1-mesa-dev libwayland-dev libxkbcommon-dev wayland-protocols
```

See https://github.com/stevenlovegrove/Pangolin/pull/520

But I'm curious why Pangolin would compile in that case...

**Comment by match08** [comment]
Thanks,   sudo apt install libegl1-mesa-dev libwayland-dev libxkbcommon-dev wayland-protocols, but  /usr/bin/ld: cannot find -lEGL. is Nvidia device is issues, reinstall Nvidia device is ok.

**Comment by NikolausDemmel** [comment]
I still think its an issue with Pangolin...

**Comment by match08** [comment]
Yes, Pangolin issue.
