### ISSUE TITLE
How to evaluate LDSO on  kitti_dataset

### ISSUE THREAD

**Issue by CLM666** [tum-vision/LDSO#38]
Hi, recently I am evaluating ldso on  kitti_dataset  ,  one problem is the stamps of dso result file are not in order (not ascending, always 0.1~0.9 )  , so I can not compare it with kitti_ground_truth whose stamps are ascending . And I print id instead of stamps just like ldso did now.
I saw ldso has  been evaluated  on  kitti_dataset , so I wonder how to do it, please help me to solve it  if it is possible. Thanks a lot!

**Comment by CLM666** [comment]
I have solved it  according to the format of ldso_result file . Thanks  very much!

**Comment by omerfy** [comment]
> I have solved it according to the format of ldso_result file . Thanks very much!

Hi, how did you solved the problem. While ground_truth has 12 columns, the result has 13 column. I'm waiting the first column to be timestamp. As you said,  the first column give the stamps only, and also the second one is not in order and between 0.1 - 0.9. Must i delete a column or something like that. 

Thanks
