### ISSUE TITLE
DBoW3 build fails with error:static assertion failed: std::map must have the same value_type as its allocator

### ISSUE THREAD

**Issue by optiluca** [tum-vision/LDSO#4]
Fresh install of 18.10 Cosmic Cuttlefish, I followed the documentation steps but make_project.sh fails on the first dependency with this error:

[  3%] Building CXX object src/CMakeFiles/ldso.dir/Frame.cc.o
cc1plus: warning: command line option ‘-Wno-duplicate-decl-specifier’ is valid for C/ObjC but not for C++
In file included from /usr/include/c++/8/map:61,
                 from /usr/include/eigen3/Eigen/SparseCore:16,
                 from /usr/include/eigen3/Eigen/Sparse:26,
                 from /usr/include/eigen3/Eigen/Eigen:2,
                 from /home/osboxes/LDSO/thirdparty/sophus/sophus.hpp:36,
                 from /home/osboxes/LDSO/thirdparty/sophus/so3.hpp:27,
                 from /home/osboxes/LDSO/thirdparty/sophus/se3.hpp:27,
                 from /home/osboxes/LDSO/include/NumTypes.h:7,
                 from /home/osboxes/LDSO/include/Frame.h:12,
                 from /home/osboxes/LDSO/src/Frame.cc:1:
/usr/include/c++/8/bits/stl_map.h: In instantiation of ‘class std::map<std::shared_ptr<ldso::Frame>, ldso::Frame::RELPOSE, std::less<std::shared_ptr<ldso::Frame> >, Eigen::aligned_allocator<ldso::Frame::RELPOSE> >’:
/home/osboxes/LDSO/include/Frame.h:158:106:   required from here
/usr/include/c++/8/bits/stl_map.h:122:21: error: static assertion failed: std::map must have the same value_type as its allocator
       static_assert(is_same<typename _Alloc::value_type, value_type>::value,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/osboxes/LDSO/thirdparty/DBoW3/src/DBoW3.h:60,
                 from /home/osboxes/LDSO/include/NumTypes.h:16,
                 from /home/osboxes/LDSO/include/Frame.h:12,
                 from /home/osboxes/LDSO/src/Frame.cc:1:
/home/osboxes/LDSO/thirdparty/DBoW3/src/Database.h:31:12: warning: ‘DBoW3::MIN_COMMON_WORDS’ defined but not used [-Wunused-variable]
 static int MIN_COMMON_WORDS = 5;
            ^~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/ldso.dir/build.make:76: src/CMakeFiles/ldso.dir/Frame.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: src/CMakeFiles/ldso.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

It looks similar to something that has recently been fixed in DSO? (https://github.com/JakobEngel/dso/issues/111 ).  Hopefully the solution will be obvious to someone who knows what they are doing :-)

**Comment by NikolausDemmel** [comment]
We have only tested on 16.04, sorry.

Thanks for linking the issue in DSO, that is very helpful. I'm not sure when I'll get round to commit a fix, but from a quick look it seems in Frame.h you need the following (untested):

```
map<shared_ptr<Frame>, RELPOSE, std::less<shared_ptr<Frame>>, Eigen::aligned_allocator<std::pair<const shared_ptr<Frame>, RELPOSE>>> poseRel;
```

There might be more places that need a fix though...

**Comment by optiluca** [comment]
Thanks for the quick feedback, I got it to build by changing the line above, as well as include/internal/OptimizationBackend/EnergyFunctional.h.  Full git diff output follows:

diff --git a/include/Frame.h b/include/Frame.h
index 8219dc7..21f5cd9 100644
--- a/include/Frame.h
+++ b/include/Frame.h
@@ -155,7 +155,8 @@ namespace ldso {
         };
 
         // relative poses within the active window
-        map<shared_ptr<Frame>, RELPOSE, std::less<shared_ptr<Frame>>, Eigen::aligned_allocator<RELPOSE>> poseRel;
+        map<shared_ptr<Frame>, RELPOSE, std::less<shared_ptr<Frame>>, Eigen::aligned_allocator<std::pair<const shared_ptr<Frame>, RELPOSE>>> poseRel;
+
 
         // Bag of Words Vector structures.
         DBoW3::BowVector bowVec;       // BoW Vector
diff --git a/include/internal/OptimizationBackend/EnergyFunctional.h b/include/internal/OptimizationBackend/EnergyFunctional.h
index b397af9..49aba91 100644
--- a/include/internal/OptimizationBackend/EnergyFunctional.h
+++ b/include/internal/OptimizationBackend/EnergyFunctional.h
@@ -174,7 +174,7 @@ namespace ldso {
             std::map<uint64_t,
                     Eigen::Vector2i,
                     std::less<uint64_t>,
-                    Eigen::aligned_allocator<std::pair<uint64_t, Eigen::Vector2i>>
+                    Eigen::aligned_allocator<std::pair< const uint64_t, Eigen::Vector2i>>
             > connectivityMap;
 
         private:
diff --git a/make_project.sh b/make_project.sh
index d1756bd..65f606d 100755
--- a/make_project.sh
+++ b/make_project.sh
:
 
         // Bag of Words Vector structures.
         DBoW3::BowVector bowVec;       // BoW Vector
diff --git a/include/internal/OptimizationBackend/EnergyFunctional.h b/include/internal/OptimizationBackend/EnergyFunctional.h
index b397af9..49aba91 100644
--- a/include/internal/OptimizationBackend/EnergyFunctional.h
+++ b/include/internal/OptimizationBackend/EnergyFunctional.h
@@ -174,7 +174,7 @@ namespace ldso {
             std::map<uint64_t,
                     Eigen::Vector2i,
                     std::less<uint64_t>,
-                    Eigen::aligned_allocator<std::pair<uint64_t, Eigen::Vector2i>>
+                    Eigen::aligned_allocator<std::pair< const uint64_t, Eigen::Vector2i>>
             > connectivityMap;
 
         private:
diff --git a/make_project.sh b/make_project.sh
index d1756bd..65f606d 100755


Thanks!

**Comment by NikolausDemmel** [comment]
Let's leave this open until we fixed it in the code.

**Comment by NikolausDemmel** [comment]
Fixed with https://github.com/tum-vision/LDSO/commit/38a5cab9b41948c5de42a672d9b33d9019a9c053
