### ISSUE TITLE
the camera.txt include what information about camera?how to extract camera information?

### ISSUE THREAD

**Issue by zpp1996** [tum-vision/LDSO#41]

**Comment by NikolausDemmel** [comment]
https://github.com/JakobEngel/dso/blob/master/README.md#geometric-calibration-file

**Comment by zpp1996** [comment]
if I want to make my dataset,the times.txt ,pcalib.txt and statistics.txt how can I get?

**Comment by NikolausDemmel** [comment]
Please respect other people's time by not just posting single-sentence questions without context. Clearly describe your issue, demonstrate that you have already done some research and what you have found out, then ask **specific** questions on the points that remain unclear. Then *maybe* someone can help.
