### ISSUE TITLE
LoopClosing issue

### ISSUE THREAD

**Issue by bokunobaka** [tum-vision/LDSO#47]
Master branch, no changes made.
Compilation works.
Running with loopclosing=0 works.
OpenCV 4.1.2-dev
Running on TUM Sequence 21

Enabling loopclosing fails at random frames.

```
./bin/run_dso_tum_mono preset=0 files=../data/tum/sequences/21/images.zip vignette=../data/tum/sequences/21/vignette.png calib=../data/tum/sequences/21/camera.txt gamma=../data/tum/sequences/21/pcalib.txt nogui=1 loopclosing=1
...
...
I0124 16:02:59.402202  3446 FullSystem.cc:1283] new features features created: 1009
I0124 16:02:59.402240  3446 FullSystem.cc:578] marg frame 81
I0124 16:02:59.407384  3446 FullSystem.cc:590] make keyframe done
I0124 16:02:59.407413  3446 FullSystem.cc:155] add active frame returned

I0124 16:02:59.413882  3445 LoopClosing.cc:125] candidate kf id: 3, max id: 42, min id: 25
I0124 16:02:59.413908  3445 LoopClosing.cc:140] add loop candidate from 3, current: 43, score: 0.0917464
I0124 16:02:59.414050  3445 LoopClosing.cc:166] matches: 21
I0124 16:02:59.418810  3446 FullSystem.cc:73] *** taking frame 133 ***
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.1.2-dev) /path/opencv/modules/calib3d/src/calibration.cpp:1171: error: (-2:Unspecified error) in function 'void cvFindExtrinsicCameraParams2(const CvMat*, const CvMat*, const CvMat*, const CvMat*, CvMat*, CvMat*, int)'
> DLT algorithm needs at least 6 points for pose estimation from 3D-2D point correspondences. (expected: 'count >= 6'), where
>     'count' is 5
> must be greater than or equal to
>     '6' is 6

Aborted (core dumped)
```
The error happens on different frames. With luck it sometimes finishes with no errors, but there is something definitely wrong somewhere. Maybe some race condition?

Any suggestions?

Edit: Same issue appears on other datasets as well (Kitti, EuRoC).

**Comment by NikolausDemmel** [comment]
Looks like this might come from within `cv::solvePnPRansac` in `https://github.com/tum-vision/LDSO/blob/1c1e3c90c68c48e904607ce36db6eac134852190/src/frontend/LoopClosing.cc#L206-L209`.

Can you try to debug and see what's going on inside? In our code, it seems we pass at least 10 matches (see the lines right before).

**Comment by tanzby** [comment]
I try to wrap  a `try...catch` block to `cv::solvePnPRansac` then it breaks in `catch` with 25 matches.

**Comment by NikolausDemmel** [comment]
Not sure if it's an issue with OpenCV or with the way we call it. Maybe you can run in the debugger and check the opencv code (build it in debug mode if you can). Or check online for this issue with `solvePnPRansac` and see if there are any hints.

**Comment by mgladkova** [comment]
@bokunobaka can you try OpenCV version 2.x? I also faced a similar issue with OpenCV 3.4 and that was a quick fix to make LDSO work.

**Comment by NikolausDemmel** [comment]
Thanks for the comments. On master there is now a try ... catch: https://github.com/tum-vision/LDSO/commit/9b0c48cfd3b3ee95a8dbf1aef2371ed4fca6f81a

I'm curious why lowering the confidence avoids the issue. I'd expect more iterations given higher confidence, and thus more chance to find an inlier set of at least 6 points.

**Comment by NikolausDemmel** [comment]
PS: Please reopen, if it still occurs with the fix from master.
