### ISSUE TITLE
A question about evaluation

### ISSUE THREAD

**Issue by cians** [tum-vision/LDSO#6]
Thank you for opening your codes!  I find you optimized the keyframes poses in loop closure.  I wonder if I understand the following correctly:
1. Do those non key frames poses remain  the state of not optimized(noloop) ?  Is the ATE errors compared with ground truth  only used the special part (Screening according to keyframe id) of ground truth in your paper? 
@gaoxiang12

**Comment by gaoxiang12** [comment]
Hi @cians ,
ATE is only evaluated on key-frames. The MATLAB evaluation code is in the DSO webpage: [https://vision.in.tum.de/research/vslam/dso](https://vision.in.tum.de/research/vslam/dso). The non-keyframes are not used in this repo, but you can easily get a interpolated value from the adjacient keyframe poses if needed.
