### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by Xuan-1998** [tum-vision/LDSO#64]
How to measure the accuracy? Are there any stats or numbers for that?

**Comment by mgladkova** [comment]
Hi @Xuan-1998,
To evaluate a camera trajectory with and without global pose graph optimization you can utilize [printResult function](https://github.com/tum-vision/LDSO/blob/master/src/frontend/FullSystem.cc#L1920). To assess a 3D map you can parse pointcloud from [saveAsPLYFile method](https://github.com/tum-vision/LDSO/blob/master/src/frontend/DSOViewer.cc#L660). If you are interested in the system accuracy on some public datasets, you can refer to [the original paper](https://arxiv.org/pdf/1808.01111.pdf) for relevant results and metrics.
