### ISSUE TITLE
compilation error with Opencv

### ISSUE THREAD

**Issue by mrgransky** [tum-vision/LDSO#7]
Hi,
I tried to compile LDSO on my Ubuntu 16.04 with opencv 3.3.1, following the readme page. However, I happen to get the following error related to opencv.

It seems opencv 3.3.1 is quite outdated for this `undefined reference to cv::Mat::updateContinuityFlag()`

![ldsoerror](https://user-images.githubusercontent.com/11946010/48060726-7a368380-e1c5-11e8-90e2-b9e9fe7881c6.png)

Does anybody know how to fix this problem?
Cheers

**Comment by NikolausDemmel** [comment]
I think 16.04 comes with OpenCV 2.4. Have you tried with that?

**Comment by mrgransky** [comment]
I googled this error, somebody in openCV forum has recommended to update to 3.4.3 ([link](http://answers.opencv.org/question/198488/undefined-reference-to-cvmatupdatecontinuityflag/)).

I compiled my opencv again following [this tutoria](https://www.youtube.com/watch?v=0vjC2UHptU4)l, but I still have the same issue since my current version is still 3.3.1 as printed in terminal.

**Comment by mrgransky** [comment]
I managed to fix that error by replacing
`find_package(OpenCV REQUIRED)`
with
`find_package(OpenCV  2.4 REQUIRED)` in `/home/path/to/LDSO/CMakeLists.txt`.

This is a new error I am facing now again related to opencv:

![ldsoerror](https://user-images.githubusercontent.com/11946010/48144444-8ef44380-e2b9-11e8-9154-b29e925516cc.png)

I tried to add `-lopencv_core` to 
```
set( THIRD_PARTY_LIBS
        ${OpenCV_LIBS}
        ${GLOG_LIBRARY}
        ${Pangolin_LIBRARIES}
        ${PROJECT_SOURCE_DIR}/thirdparty/g2o/lib/libg2o${CMAKE_SHARED_LIBRARY_SUFFIX}
        ${PROJECT_SOURCE_DIR}/thirdparty/DBoW3/build/src/libDBoW3${CMAKE_SHARED_LIBRARY_SUFFIX}
        ${LIBZIP_LIBRARY}
	-lopencv_core
)
```
but this does not seem to fix my problem.

**Comment by shadowver** [comment]
it looks like you are still using opencv3.3.1 based on your error message. However,  CMake tries to locate opencv 2.4 as you replace the original cmake line and WONT be able to find such library. In addition, it appears that your libopencv is not a default location such as /usr/local/lib. Hence, you may want to edit ld.so.conf to ensure cmake can find the share libs...

**Comment by NikolausDemmel** [comment]
As @shadowver mentions, it looks like the versions are still messed up. Make sure cmake picks the right one. Removing your `build` folder and rerunning cmake cleanly may help.

**Comment by mrgransky** [comment]
Yes, thank you!
I made a mistake to install opencv from an external link.

The command,

`$  sudo apt-get install libopencv-dev `

is enough for compiling the project.
