### ISSUE TITLE
Some required libraries are not in the dependencies list

### ISSUE THREAD

**Issue by alex-fu27** [tum-vision/LDSO#72]
Someone needs to add the following libraries to the dependencies list, but I can't create a pull request because I am not on debian and do not know what to add to the `install_dependencies.sh`:
* Pangolin
* glew

**Comment by zovelsanj** [comment]
I suggest you install these packages from source

**Comment by alex-fu27** [comment]
You are getting me wrong - I mean I know how to install all of these, I  just didn't know what to install. So I looked into the `install_dependencies.sh` and didn't install Pangolin and glew, because they are not in there. But I found that you have an actual list of dependencies (glew still missing) in the README, so I am closing this here.
