### ISSUE TITLE
terminate called after throwing an instance of 'std::system_error'

### ISSUE THREAD

**Issue by LittleByLittle2** [tum-vision/LDSO#8]
Hi, I run the code and the input is right and can see the point cloud on Pangolin.

But when the program is finished, it will produce the system error:
```
I1204 11:44:46.282876 30182 run_dso_tum_mono.cc:674] EXIT NOW!
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
./run_indoor_huaweo.sh: line 8: 30182 Aborted                 (core dumped) ./bin/run_dso_tum_mono files=./images calib=./camera.tx
t mode=2 preset=0 nogui=1 start=1000 end=1100
```

You can see the program is run to the last line of code "EXIT NOW", but there is one system error throwing.  I think this may be the error call the FullSystem destructor, can you give me some advice on it?

**Comment by NikolausDemmel** [comment]
Well, I suggest to run in the debugger and see where the exception is thrown.

**Comment by NikolausDemmel** [comment]
Well, I suggest to run in the debugger and see where the exception is thrown.

**Comment by NikolausDemmel** [comment]
Did you find what went wrong?

**Comment by LittleByLittle2** [comment]
> Did you find what went wrong?

No, I think it is about mutex broken. But currently I can save the final results, so I ignore this error.

**Comment by NikolausDemmel** [comment]
#18 addresses also clean exiting.
