### ISSUE TITLE
Bow dictionary problem

### ISSUE THREAD

**Issue by LittleByLittle2** [tum-vision/LDSO#9]
What kind of data set is uesd to build the BoW dictionary of LDSO?

Than you.

**Comment by gaoxiang12** [comment]
I just use the suggested dictionary in dbow3, see https://github.com/rmsalinas/DBow3 for details. You may also train another dict with your own data.

**Comment by LittleByLittle2** [comment]
> I just use the suggested dictionary in dbow3, see https://github.com/rmsalinas/DBow3 for details. You may also train another dict with your own data.

Thank you.
